/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedBaseBreadcrumb: typeof import('./components/shared/BaseBreadcrumb.vue')['default']
    SharedComponentTitle: typeof import('./components/shared/ComponentTitle.vue')['default']
    SharedUiParentCard: typeof import('./components/shared/UiParentCard.vue')['default']
    SharedUiTitleCard: typeof import('./components/shared/UiTitleCard.vue')['default']
  }
}
